#ifndef PT100_LOGGER_FRAM_LAYOUT_H_
#define PT100_LOGGER_FRAM_LAYOUT_H_

#include "sdkconfig.h"

#define FRAM_TOTAL_BYTES CONFIG_APP_FRAM_SIZE_BYTES
#define FRAM_ERRLOG_BYTES CONFIG_APP_FRAM_ERRLOG_BYTES
#define FRAM_DATA_BYTES (FRAM_TOTAL_BYTES - FRAM_ERRLOG_BYTES)
#define FRAM_ERRLOG_BASE FRAM_DATA_BYTES

#if FRAM_ERRLOG_BYTES >= FRAM_TOTAL_BYTES
#error "FRAM_ERRLOG_BYTES must be smaller than FRAM_TOTAL_BYTES"
#endif

#endif // PT100_LOGGER_FRAM_LAYOUT_H_
