#include "bsc_status.h"

const char *bsc_status_name(bsc_status_t status) {
  switch (status) {
  case BSC_STATUS_OK:
    return "BSC_STATUS_OK";
  case BSC_STATUS_NO_INPUT:
    return "BSC_STATUS_NO_INPUT";
  case BSC_STATUS_LINE_TOO_LONG:
    return "BSC_STATUS_LINE_TOO_LONG";
  case BSC_STATUS_TOKEN_TOO_LONG:
    return "BSC_STATUS_TOKEN_TOO_LONG";
  case BSC_STATUS_TOO_MANY_TOKENS:
    return "BSC_STATUS_TOO_MANY_TOKENS";
  case BSC_STATUS_UNTERMINATED_QUOTE:
    return "BSC_STATUS_UNTERMINATED_QUOTE";
  case BSC_STATUS_INVALID_SYNTAX:
    return "BSC_STATUS_INVALID_SYNTAX";
  case BSC_STATUS_UNKNOWN_COMMAND:
    return "BSC_STATUS_UNKNOWN_COMMAND";
  case BSC_STATUS_AMBIGUOUS_COMMAND:
    return "BSC_STATUS_AMBIGUOUS_COMMAND";
  case BSC_STATUS_GROUP_REQUIRES_SUBCOMMAND:
    return "BSC_STATUS_GROUP_REQUIRES_SUBCOMMAND";
  case BSC_STATUS_MISSING_ARGUMENT:
    return "BSC_STATUS_MISSING_ARGUMENT";
  case BSC_STATUS_EXTRA_ARGUMENT:
    return "BSC_STATUS_EXTRA_ARGUMENT";
  case BSC_STATUS_INVALID_ARGUMENT_TYPE:
    return "BSC_STATUS_INVALID_ARGUMENT_TYPE";
  case BSC_STATUS_ARGUMENT_OUT_OF_RANGE:
    return "BSC_STATUS_ARGUMENT_OUT_OF_RANGE";
  case BSC_STATUS_ARGUMENT_TOO_LONG:
    return "BSC_STATUS_ARGUMENT_TOO_LONG";
  case BSC_STATUS_INVALID_ENUM_VALUE:
    return "BSC_STATUS_INVALID_ENUM_VALUE";
  case BSC_STATUS_ACCESS_DENIED:
    return "BSC_STATUS_ACCESS_DENIED";
  case BSC_STATUS_OUTPUT_TRUNCATED:
    return "BSC_STATUS_OUTPUT_TRUNCATED";
  case BSC_STATUS_APP_ERROR:
    return "BSC_STATUS_APP_ERROR";
  case BSC_STATUS_INTERNAL_ERROR:
    return "BSC_STATUS_INTERNAL_ERROR";
  default:
    return "BSC_STATUS_UNKNOWN";
  }
}
